### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by drworm75**
Challenge complete!

### CODE REVIEW

**Comment by zoeames** [comment]
@drworm75 looks great!  Just a little code cleanup needed.  Remove all the commented out code from your JS file.  Also rename your index file so it ends with html

**Comment by drworm75** [comment]
@zoeames  fixed the issues.

**Comment by drworm75** [comment]
@rousell I think I'm done. :)

**Comment by drworm75** [comment]
@morecallan quiz complete

**Comment by drworm75** [comment]
@morecallan removed event listener from html, added to js

**Comment by morecallan** [comment]
👍 good one!

**Pull request merged**
